apiVersion: v1
kind: Service
metadata:
  name: streamlit-task-app-svc
  labels:
    component: streamlit-task-app
spec:
  type: NodePort
  selector:
    component: streamlit-task-app
  ports:
  - protocol: TCP
    port: 8501
    nodePort: 30080
    name: https