---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-task-app
  labels:
    component: streamlit-task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: streamlit-task-app
  template:
    metadata:
      labels:
        component: streamlit-task-app
    spec:
      containers:
      - name: streamlit-task-app
        image: ahmedmq/streamlit-task-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/keys/keys.json
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: streamlit-task-app-volume
          mountPath: /tmp/keys
          readOnly: true
      volumes:
      - name: streamlit-task-app-volume
        secret:
          secretName: streamlit-task-app-secret
          items:
          - key: cred_json_file
            path: keys.json
