name: Streamlit Task App workflow

env:
  IMAGE_NAME: "streamlit-task-app"

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
        - name: Code Checkout
          uses: actions/checkout@v2

        - name: Build docker image
          run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/$(echo $IMAGE_NAME):latest

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push image to Dockerhub
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$(echo $IMAGE_NAME):latest